import React from 'react'
import AutoGeneratedText from '../components/typing/AutoGeneratedText'
import UserGeneratedText from '../components/typing/UserGeneratedText'

const TextDisplay = ({ isAutoGenerated, activeChar, onLevelChange, onResetLevel, onProgressChange, updateAccuracyData, isTracking, setIsTracking, handleTextCompleted }) => {
    return (
        <div className='text-display'>
            {isAutoGenerated 
                ? <AutoGeneratedText 
                    activeChar={activeChar} 
                    onLevelChange={onLevelChange} 
                    onResetLevel={onResetLevel} 
                    onProgressChange={onProgressChange} 
                    updateAccuracyData={updateAccuracyData}
                />
                : <UserGeneratedText 
                    activeChar={activeChar} 
                    onProgressChange={onProgressChange}
                    updateAccuracyData={updateAccuracyData}
                    isTracking={isTracking}
                    setIsTracking={setIsTracking}
                    handleTextCompleted={handleTextCompleted}
                />
            }
        </div>
    )
}

export default TextDisplay
