import React from 'react'
import AutoGeneratedText from '../components/typing/AutoGeneratedText'
import UserGeneratedText from '../components/typing/UserGeneratedText'

const TextDisplay = ({ isAutoGenerated, activeChar, onLevelChange, onResetLevel, onProgressChange }) => {
    return (
        <div className='text-display'>
            {isAutoGenerated 
                ? <AutoGeneratedText activeChar={activeChar} onLevelChange={onLevelChange} onResetLevel={onResetLevel} onProgressChange={onProgressChange} />
                : <UserGeneratedText activeChar={activeChar} onProgressChange={onProgressChange}/>}
        </div>
    )
}

export default TextDisplay
