import React from 'react'
import { IconButton } from '@mui/material'
import DataObjectIcon from '@mui/icons-material/DataObject'
import TitleIcon from '@mui/icons-material/Title'


const TypingSwitcher = ({ isAutoGenerated, toggleMode }) => {
    return (
        <div>
            <IconButton onClick={toggleMode} color='inherit'>
                {isAutoGenerated ? <DataObjectIcon /> : <TitleIcon /> }
            </IconButton>
        </div>
    )
}

export default TypingSwitcher
