import React from 'react'
import { IconButton } from '@mui/material'
import DataObjectIcon from '@mui/icons-material/DataObject'
import TitleIcon from '@mui/icons-material/Title'


const TypingSwitcher = ({ isAutoGenerated, toggleMode, textDisplayRef }) => {
    const handleKeyDown = () => {
        toggleMode()

        if (textDisplayRef.current) {
            textDisplayRef.current.focus()
        }
    }

    return (
        <div>
            <IconButton 
                onClick={handleKeyDown} 
                color='inherit'
                aria-label={isAutoGenerated ? 'Switch to manual typing' : 'Switch to auto-generated text'}
            >
                {isAutoGenerated ? <DataObjectIcon /> : <TitleIcon /> }
            </IconButton>
        </div>
    )
}

export default TypingSwitcher
