import React from 'react'
import { IconButton } from '@mui/material'
import DataObjectIcon from '@mui/icons-material/DataObject'
import TitleIcon from '@mui/icons-material/Title'


const TypingSwitcher = ({ isAutoGenerated, toggleMode, textDisplayRef }) => {
    const handleKeyDown = () => {
        toggleMode()

        if (textDisplayRef.current) {
            textDisplayRef.current.focus()
        }
    }

    return (
        <div>
            <IconButton onClick={handleKeyDown} color='inherit'>
                {isAutoGenerated ? <DataObjectIcon /> : <TitleIcon /> }
            </IconButton>
        </div>
    )
}

export default TypingSwitcher
