//Array de todas las teclas, subdividido en arrays que representan cada fila del teclado 65%

const keys = [
    [
        { chart: 'esc', shift: '', alt: '', size: 'esc' },
        { chart: '1', shift: '!', alt: '|', size: 'default' },
        { chart: '2', shift: '"', alt: '@', size: 'default' },
        { chart: '3', shift: '·', alt: '#', size: 'default' },
        { chart: '4', shift: '$', alt: '', size: 'default' },
        { chart: '5', shift: '%', alt: '€', size: 'default' },
        { chart: '6', shift: '&', alt: '¬', size: 'default' },
        { chart: '7', shift: '/', alt: '', size: 'default' },
        { chart: '8', shift: '(', alt: '', size: 'default' },
        { chart: '9', shift: ')', alt: '', size: 'default' },
        { chart: '0', shift: '=', alt: '', size: 'default' },
        { chart: "'", shift: '?', alt: '', size: 'default' },
        { chart: '¡', shift: '¿', alt: '', size: 'default' },
        { chart: '←backspace', shift: '', alt: '', size: 'backspace' },
        { chart: 'º', shift: 'ª', alt: '\\', size: 'default' },
    ],
    [
        { chart: '⇥', shift: '', alt: '', size: 'tab' },
        { chart: 'Q', shift: '', alt: '', size: 'default' },
        { chart: 'W', shift: '', alt: '', size: 'default' },
        { chart: 'E', shift: '', alt: '€', size: 'default' },
        { chart: 'R', shift: '', alt: '', size: 'default' },
        { chart: 'T', shift: '', alt: '', size: 'default' },
        { chart: 'Y', shift: '', alt: '', size: 'default' },
        { chart: 'U', shift: '', alt: '', size: 'default' },
        { chart: 'I', shift: '', alt: '', size: 'default' },
        { chart: 'O', shift: '', alt: '', size: 'default' },
        { chart: 'P', shift: '', alt: '', size: 'default' },
        { chart: '`', shift: '^', alt: '[', size: 'default' },
        { chart: '+', shift: '*', alt: ']', size: 'default' },
        { chart: 'Ç', shift: '', alt: '}', size: 'cetrencada' },
        { chart: '⌫', shift: '', alt: '', size: 'default' },
    ],
    [
        { chart: 'capslock', shift: '', alt: '', size: 'capslock' },
        { chart: 'A', shift: '', alt: '', size: 'default' },
        { chart: 'S', shift: '', alt: '', size: 'default' },
        { chart: 'D', shift: '', alt: '', size: 'default' },
        { chart: 'F', shift: '', alt: '', size: 'default' },
        { chart: 'G', shift: '', alt: '', size: 'default' },
        { chart: 'H', shift: '', alt: '', size: 'default' },
        { chart: 'J', shift: '', alt: '', size: 'default' },
        { chart: 'K', shift: '', alt: '', size: 'default' },
        { chart: 'L', shift: '', alt: '', size: 'default' },
        { chart: 'Ñ', shift: '', alt: '', size: 'default' },
        { chart: '´', shift: '¨', alt: '{', size: 'default' },
        { chart: '⏎', shift: '', alt: '', size: 'enter' },
        { chart: 'pgup', shift: '', alt: '', size: 'pgup' },
    ],
    [
        { chart: '⇧', shift: '', alt: '', size: 'enter' },
        { chart: 'Z', shift: '', alt: '', size: 'default' },
        { chart: 'X', shift: '', alt: '', size: 'default' },
        { chart: 'C', shift: '', alt: '', size: 'default' },
        { chart: 'V', shift: '', alt: '', size: 'default' },
        { chart: 'B', shift: '', alt: '', size: 'default' },
        { chart: 'N', shift: '', alt: '', size: 'default' },
        { chart: 'M', shift: '', alt: '', size: 'default' },
        { chart: ',', shift: ';', alt: '<', size: 'default' },
        { chart: '.', shift: ':', alt: '>', size: 'default' },
        { chart: '-', shift: '_', alt: '', size: 'default' },
        { chart: '⇧', shift: '', alt: '', size: 'capslock' },
        { chart: '↑', shift: '', alt: '', size: 'arrows' },
        { chart: 'pgdn', shift: '', alt: '', size: 'pgdn' },
    ],
    [
        { chart: 'ctrl', shift: '', alt: '', size: 'ctrl' },
        { chart: 'option', shift: '', alt: '', size: 'ctrl' },
        { chart: 'alt', shift: '', alt: '', size: 'ctrl' },
        { chart: '', shift: '', alt: '', size: 'space' },
        { chart: 'alt', shift: '', alt: '', size: 'fn' },
        { chart: 'fn', shift: '', alt: '', size: 'fn' },
        { chart: 'ctrl', shift: '', alt: '', size: 'fn' },
        { chart: '←', shift: '', alt: '', size: 'arrows' },
        { chart: '↓', shift: '', alt: '', size: 'arrows' },
        { chart: '→', shift: '', alt: '', size: 'arrows' },
    ],
]

export default keys;