//Array de todas las teclas, subdividido en arrays que representan cada fila del teclado 65%

const keys = [
    [
        { chart: 'esc', shift: '', alt: '', size: 'esc', keyListener: 'Escape', modifier: '' },
        { chart: '1', shift: '!', alt: '|', size: 'default', keyListener: '1', modifier: '' },
        { chart: '2', shift: '"', alt: '@', size: 'default', keyListener: '2', modifier: '' },
        { chart: '3', shift: '·', alt: '#', size: 'default', keyListener: '3', modifier: '' },
        { chart: '4', shift: '$', alt: '', size: 'default', keyListener: '4', modifier: '' },
        { chart: '5', shift: '%', alt: '€', size: 'default', keyListener: '5', modifier: '' },
        { chart: '6', shift: '&', alt: '¬', size: 'default', keyListener: '6', modifier: '' },
        { chart: '7', shift: '/', alt: '', size: 'default', keyListener: '7', modifier: '' },
        { chart: '8', shift: '(', alt: '', size: 'default', keyListener: '8', modifier: '' },
        { chart: '9', shift: ')', alt: '', size: 'default', keyListener: '9', modifier: '' },
        { chart: '0', shift: '=', alt: '', size: 'default', keyListener: '0', modifier: '' },
        { chart: "'", shift: '?', alt: '', size: 'default', keyListener: "'", modifier: '' },
        { chart: '¡', shift: '¿', alt: '', size: 'default', keyListener: '¡', modifier: '' },
        { chart: '←backspace', shift: '', alt: '', size: 'backspace', keyListener: 'Backspace', modifier: '' },
        { chart: 'º', shift: 'ª', alt: '\\', size: 'default', keyListener: 'º', modifier: '' },
    ],
    [
        { chart: '⇥', shift: '', alt: '', size: 'tab', keyListener: 'Tab', modifier: '' },
        { chart: 'Q', shift: '', alt: '', size: 'default', keyListener: 'q', modifier: '' },
        { chart: 'W', shift: '', alt: '', size: 'default', keyListener: 'w', modifier: '' },
        { chart: 'E', shift: '', alt: '€', size: 'default', keyListener: 'e', modifier: '' },
        { chart: 'R', shift: '', alt: '', size: 'default', keyListener: 'r', modifier: '' },
        { chart: 'T', shift: '', alt: '', size: 'default', keyListener: 't', modifier: '' },
        { chart: 'Y', shift: '', alt: '', size: 'default', keyListener: 'y', modifier: '' },
        { chart: 'U', shift: '', alt: '', size: 'default', keyListener: 'u', modifier: '' },
        { chart: 'I', shift: '', alt: '', size: 'default', keyListener: 'i', modifier: '' },
        { chart: 'O', shift: '', alt: '', size: 'default', keyListener: 'o', modifier: '' },
        { chart: 'P', shift: '', alt: '', size: 'default', keyListener: 'p', modifier: '' },
        { chart: '`', shift: '^', alt: '[', size: 'default', keyListener: 'Dead', modifier: '' },
        { chart: '+', shift: '*', alt: ']', size: 'default', keyListener: '+', modifier: '' },
        { chart: 'Ç', shift: '', alt: '}', size: 'cetrencada', keyListener: 'ç', modifier: '' },
        { chart: '⌫', shift: '', alt: '', size: 'default', keyListener: 'Delete', modifier: '' },
    ],
    [
        { chart: 'capslock', shift: '', alt: '', size: 'capslock', keyListener: 'CapsLock', modifier: '' },
        { chart: 'A', shift: '', alt: '', size: 'default', keyListener: 'a', modifier: '' },
        { chart: 'S', shift: '', alt: '', size: 'default', keyListener: 's', modifier: '' },
        { chart: 'D', shift: '', alt: '', size: 'default', keyListener: 'd', modifier: '' },
        { chart: 'F', shift: '', alt: '', size: 'default', keyListener: 'f', modifier: '' },
        { chart: 'G', shift: '', alt: '', size: 'default', keyListener: 'g', modifier: '' },
        { chart: 'H', shift: '', alt: '', size: 'default', keyListener: 'h', modifier: '' },
        { chart: 'J', shift: '', alt: '', size: 'default', keyListener: 'j', modifier: '' },
        { chart: 'K', shift: '', alt: '', size: 'default', keyListener: 'k', modifier: '' },
        { chart: 'L', shift: '', alt: '', size: 'default', keyListener: 'l', modifier: '' },
        { chart: 'Ñ', shift: '', alt: '', size: 'default', keyListener: 'ñ', modifier: '' },
        { chart: '´', shift: '¨', alt: '{', size: 'default', keyListener: 'Dead', modifier: '' },
        { chart: '⏎', shift: '', alt: '', size: 'enter', keyListener: 'Enter', modifier: '' },
        { chart: 'pgup', shift: '', alt: '', size: 'pgup', keyListener: 'PageUp', modifier: '' },
    ],
    [
        { chart: '⇧', shift: '', alt: '', size: 'enter', keyListener: 'Shift', modifier: '' },
        { chart: 'Z', shift: '', alt: '', size: 'default', keyListener: 'z', modifier: '' },
        { chart: 'X', shift: '', alt: '', size: 'default', keyListener: 'x', modifier: '' },
        { chart: 'C', shift: '', alt: '', size: 'default', keyListener: 'c', modifier: '' },
        { chart: 'V', shift: '', alt: '', size: 'default', keyListener: 'v', modifier: '' },
        { chart: 'B', shift: '', alt: '', size: 'default', keyListener: 'b', modifier: '' },
        { chart: 'N', shift: '', alt: '', size: 'default', keyListener: 'n', modifier: '' },
        { chart: 'M', shift: '', alt: '', size: 'default', keyListener: 'm', modifier: '' },
        { chart: ',', shift: ';', alt: '<', size: 'default', keyListener: ',', modifier: '' },
        { chart: '.', shift: ':', alt: '>', size: 'default', keyListener: '.', modifier: '' },
        { chart: '-', shift: '_', alt: '', size: 'default', keyListener: '-', modifier: '' },
        { chart: '⇧', shift: '', alt: '', size: 'capslock', keyListener: 'Shift', modifier: '' },
        { chart: '↑', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowUp', modifier: '' },
        { chart: 'pgdn', shift: '', alt: '', size: 'pgdn', keyListener: 'PageDown', modifier: '' },
    ],
    [
        { chart: 'ctrl', shift: '', alt: '', size: 'ctrl', keyListener: 'Control', modifier: '' },
        { chart: 'option', shift: '', alt: '', size: 'ctrl', keyListener: 'Meta', modifier: '' },
        { chart: 'alt', shift: '', alt: '', size: 'ctrl', keyListener: 'Alt', modifier: '' },
        { chart: '', shift: '', alt: '', size: 'space', keyListener: ' ', modifier: '' },
        { chart: 'alt', shift: '', alt: '', size: 'fn', keyListener: 'AltGraph', modifier: '' },
        { chart: 'fn', shift: '', alt: '', size: 'fn', keyListener: '', modifier: '' },
        { chart: 'ctrl', shift: '', alt: '', size: 'fn', keyListener: 'Control', modifier: '' },
        { chart: '←', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowLeft', modifier: '' },
        { chart: '↓', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowDown', modifier: '' },
        { chart: '→', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowRight', modifier: '' },
    ],
]

export default keys;