//Array de todas las teclas, subdividido en arrays que representan cada fila del teclado 65%

const keys = [
    [
        { chart: 'esc', shift: '', alt: '', size: 'esc', keyListener: 'Escape' },
        { chart: '1', shift: '!', alt: '|', size: 'default', keyListener: 'Digit1' },
        { chart: '2', shift: '"', alt: '@', size: 'default', keyListener: 'Digit2' },
        { chart: '3', shift: '·', alt: '#', size: 'default', keyListener: 'Digit3' },
        { chart: '4', shift: '$', alt: '', size: 'default', keyListener: 'Digit4' },
        { chart: '5', shift: '%', alt: '€', size: 'default', keyListener: 'Digit5' },
        { chart: '6', shift: '&', alt: '¬', size: 'default', keyListener: 'Digit6' },
        { chart: '7', shift: '/', alt: '', size: 'default', keyListener: 'Digit7' },
        { chart: '8', shift: '(', alt: '', size: 'default', keyListener: 'Digit8' },
        { chart: '9', shift: ')', alt: '', size: 'default', keyListener: 'Digit9' },
        { chart: '0', shift: '=', alt: '', size: 'default', keyListener: 'Digit0' },
        { chart: "'", shift: '?', alt: '', size: 'default', keyListener: "Minus" },
        { chart: '¡', shift: '¿', alt: '', size: 'default', keyListener: 'Equal' },
        { chart: '←backspace', shift: '', alt: '', size: 'backspace', keyListener: 'Backspace' },
        { chart: 'º', shift: 'ª', alt: '\\', size: 'default', keyListener: 'Backslash' },
    ],
    [
        { chart: '⇥', shift: '', alt: '', size: 'tab', keyListener: 'Tab' },
        { chart: 'Q', shift: '', alt: '', size: 'default', keyListener: 'KeyQ' },
        { chart: 'W', shift: '', alt: '', size: 'default', keyListener: 'KeyW' },
        { chart: 'E', shift: '', alt: '€', size: 'default', keyListener: 'KeyE'},
        { chart: 'R', shift: '', alt: '', size: 'default', keyListener: 'KeyR' },
        { chart: 'T', shift: '', alt: '', size: 'default', keyListener: 'KeyT' },
        { chart: 'Y', shift: '', alt: '', size: 'default', keyListener: 'KeyY' },
        { chart: 'U', shift: '', alt: '', size: 'default', keyListener: 'KeyU' },
        { chart: 'I', shift: '', alt: '', size: 'default', keyListener: 'KeyI' },
        { chart: 'O', shift: '', alt: '', size: 'default', keyListener: 'KeyO' },
        { chart: 'P', shift: '', alt: '', size: 'default', keyListener: 'KeyP' },
        { chart: '`', shift: '^', alt: '[', size: 'default', keyListener: 'BracketLeft' },
        { chart: '+', shift: '*', alt: ']', size: 'default', keyListener: 'BracketRight' },
        { chart: 'Ç', shift: '', alt: '}', size: 'cetrencada', keyListener: 'Backslash' },
        { chart: '⌫', shift: '', alt: '', size: 'default', keyListener: 'Delete' },
    ],
    [
        { chart: 'capslock', shift: '', alt: '', size: 'capslock', keyListener: 'CapsLock' },
        { chart: 'A', shift: '', alt: '', size: 'default', keyListener: 'KeyA' },
        { chart: 'S', shift: '', alt: '', size: 'default', keyListener: 'KeyS' },
        { chart: 'D', shift: '', alt: '', size: 'default', keyListener: 'KeyD' },
        { chart: 'F', shift: '', alt: '', size: 'default', keyListener: 'KeyF' },
        { chart: 'G', shift: '', alt: '', size: 'default', keyListener: 'KeyG' },
        { chart: 'H', shift: '', alt: '', size: 'default', keyListener: 'KeyH' },
        { chart: 'J', shift: '', alt: '', size: 'default', keyListener: 'KeyJ' },
        { chart: 'K', shift: '', alt: '', size: 'default', keyListener: 'KeyK' },
        { chart: 'L', shift: '', alt: '', size: 'default', keyListener: 'KeyL' },
        { chart: 'Ñ', shift: '', alt: '', size: 'default', keyListener: 'Semicolon' },
        { chart: '´', shift: '¨', alt: '{', size: 'default', keyListener: 'Quote' },
        { chart: '⏎', shift: '', alt: '', size: 'enter', keyListener: 'Enter' },
        { chart: 'pgup', shift: '', alt: '', size: 'pgup', keyListener: 'PageUp' },
    ],
    [
        { chart: '⇧', shift: '', alt: '', size: 'enter', keyListener: 'ShiftLeft' },
        { chart: 'Z', shift: '', alt: '', size: 'default', keyListener: 'KeyZ' },
        { chart: 'X', shift: '', alt: '', size: 'default', keyListener: 'KeyX' },
        { chart: 'C', shift: '', alt: '', size: 'default', keyListener: 'KeyC' },
        { chart: 'V', shift: '', alt: '', size: 'default', keyListener: 'KeyV' },
        { chart: 'B', shift: '', alt: '', size: 'default', keyListener: 'KeyB' },
        { chart: 'N', shift: '', alt: '', size: 'default', keyListener: 'KeyN' },
        { chart: 'M', shift: '', alt: '', size: 'default', keyListener: 'KeyM' },
        { chart: ',', shift: ';', alt: '<', size: 'default', keyListener: 'Comma' },
        { chart: '.', shift: ':', alt: '>', size: 'default', keyListener: 'Period' },
        { chart: '-', shift: '_', alt: '', size: 'default', keyListener: 'Slash' },
        { chart: '⇧', shift: '', alt: '', size: 'Small-Shift', keyListener: 'ShiftRight' },
        { chart: '↑', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowUp' },
        { chart: 'pgdn', shift: '', alt: '', size: 'pgdn', keyListener: 'PageDown' },
    ],
    [
        { chart: 'ctrl', shift: '', alt: '', size: 'ctrl', keyListener: 'ControlLeft' },
        { chart: 'option', shift: '', alt: '', size: 'ctrl', keyListener: 'MetaLeft' },
        { chart: 'alt', shift: '', alt: '', size: 'ctrl', keyListener: 'AltLeft' },
        { chart: '', shift: '', alt: '', size: 'space', keyListener: 'Space' },
        { chart: 'alt', shift: '', alt: '', size: 'fn', keyListener: 'AltRight' },
        { chart: 'fn', shift: '', alt: '', size: 'fn', keyListener: '' },
        { chart: 'ctrl', shift: '', alt: '', size: 'fn', keyListener: 'ControlRight' },
        { chart: '←', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowLeft' },
        { chart: '↓', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowDown' },
        { chart: '→', shift: '', alt: '', size: 'arrows', keyListener: 'ArrowRight' },
    ],
]

export default keys;